# Generated by Django 3.1.2 on 2020-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to='images/', width_field=50),
        ),
    ]
